name: build and publish v8 libs
on:
  push:
    tags:
      - 'v*'

env:
  V8_VERSION: "14.3.92"

defaults:
  run:
    shell: bash

jobs:
  create-release:
    name: create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release-${{ github.ref }}
          draft: true
          prerelease: false

  build-android:
    name: android
    env:
      JOB_NAME: android
    needs: create-release
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        platform: [arm64, arm]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: compile v8
        env:
          PLATFORM: ${{ matrix.platform }}
          JOB_NAME: ${{ env.JOB_NAME }}
          WORKSPACE: ${{ github.workspace }}
        run: |
          echo "::group::Prepare v8 build environment"
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          export PATH="$GITHUB_WORKSPACE/depot_tools:${PATH}"
          gclient
          fetch v8
          echo "target_os = ['android']" >> ${{ github.workspace }}/.gclient
          cd ${{ github.workspace }}/v8
          git checkout $V8_VERSION
          gclient sync
          ./build/install-build-deps.sh
          echo "::endgroup::"
          echo "::group::Run pre-build script"
          node ${{ github.workspace }}/builder.js
          echo "::endgroup::"
          echo "::group::Compile v8 static library"
          mkdir -p out.gn/android.${{ matrix.platform }}.release/
          cp ${{ github.workspace }}/args.android.${{ matrix.platform }}.gn $GITHUB_WORKSPACE/v8/out.gn/android.${{ matrix.platform }}.release/args.gn
          gn gen out.gn/android.${{ matrix.platform }}.release
          ninja v8_monolith -C out.gn/android.${{ matrix.platform }}.release/
          gn args --list out.gn/android.${{ matrix.platform }}.release
          echo "::endgroup::"
          echo "::group::Compress artifacts"
          zip -j ../libv8_monolith-${{ env.JOB_NAME }}-${{ matrix.platform }}.zip out.gn/android.${{ matrix.platform }}.release/obj/libv8_monolith.a
          if [ "${{ matrix.platform }}" = "arm64" ]; then
            zip -r ../include-${{ env.JOB_NAME }}.zip include
          fi
          ls -a
          echo "::endgroup::"
      - name: Upload static library
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/libv8_monolith-${{ env.JOB_NAME }}-${{ matrix.platform }}.zip
          asset_name: libv8_monolith-${{ env.JOB_NAME }}-${{ matrix.platform }}.zip
          asset_content_type: application/zip
      - name: Upload include
        if: matrix.platform == 'arm64'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/include-${{ env.JOB_NAME }}.zip
          asset_name: include-${{ env.JOB_NAME }}.zip
          asset_content_type: application/zip

  build-mac:
    name: mac
    env:
      JOB_NAME: mac
    needs: create-release
    runs-on: macos-15
    strategy:
      fail-fast: false
      matrix:
        platform: [arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: build v8
        env:
          PLATFORM: ${{ matrix.platform }}
          JOB_NAME: ${{ env.JOB_NAME }}
          WORKSPACE: ${{ github.workspace }}
        run: |
          echo "::group::Prepare v8 build environment"
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          export PATH="$GITHUB_WORKSPACE/depot_tools:${PATH}"
          gclient
          fetch v8
          cd ${{ github.workspace }}/v8
          git checkout $V8_VERSION
          gclient sync
          echo "::endgroup::"
          echo "::group::Run pre-build script"
          node ${{ github.workspace }}/builder.js
          echo "::endgroup::"
          echo "::group::Compile v8 static library"
          mkdir -p out.gn/mac.${{ matrix.platform }}.release/
          cp ${{ github.workspace }}/args.mac.${{ matrix.platform }}.gn ${{ github.workspace }}/v8/out.gn/mac.${{ matrix.platform }}.release/args.gn
          gn gen out.gn/mac.${{ matrix.platform }}.release
          ninja v8_monolith -C out.gn/mac.${{ matrix.platform }}.release/
          gn args --list out.gn/mac.${{ matrix.platform }}.release
          echo "::endgroup::"
          echo "::group::Compress artifacts"
          zip -j ../libv8_monolith-${{ env.JOB_NAME }}-${{ matrix.platform }}.zip out.gn/mac.${{ matrix.platform }}.release/obj/libv8_monolith.a
          if [ "${{ matrix.platform }}" = "arm64" ]; then
            zip -r ../include-${{ env.JOB_NAME }}.zip include
          fi
          ls -a
          echo "::endgroup::"
      - name: Upload static library
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/libv8_monolith-${{ env.JOB_NAME }}-${{ matrix.platform }}.zip
          asset_name: libv8_monolith-${{ env.JOB_NAME }}-${{ matrix.platform }}.zip
          asset_content_type: application/zip
      - name: Upload include
        if: matrix.platform == 'arm64'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/include-${{ env.JOB_NAME }}.zip
          asset_name: include-${{ env.JOB_NAME }}.zip
          asset_content_type: application/zip

  build-ios:
    name: ios
    env:
      JOB_NAME: ios
    needs: create-release
    runs-on: macos-26
    strategy:
      fail-fast: false
      matrix:
        platform: [arm64, arm64.simulator]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: build v8
        env:
          PLATFORM: ${{ matrix.platform }}
          JOB_NAME: ${{ env.JOB_NAME }}
          WORKSPACE: ${{ github.workspace }}
        run: |
          echo "::group::Prepare v8 build environment"
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          export PATH="$GITHUB_WORKSPACE/depot_tools:${PATH}"
          gclient
          fetch v8
          echo "target_os = ['ios']" >> ${{ github.workspace }}/.gclient
          cd ${{ github.workspace }}/v8
          git checkout $V8_VERSION
          gclient sync
          echo "::endgroup::"
          echo "::group::Run pre-build script"
          node ${{ github.workspace }}/builder.js
          echo "::endgroup::"
          echo "::group::Compile v8 static library"
          mkdir -p out.gn/ios.${{ matrix.platform }}.release/
          cp ${{ github.workspace }}/args.ios.${{ matrix.platform }}.gn ${{ github.workspace }}/v8/out.gn/ios.${{ matrix.platform }}.release/args.gn
          gn gen out.gn/ios.${{ matrix.platform }}.release
          ninja v8_monolith -C out.gn/ios.${{ matrix.platform }}.release/
          gn args --list out.gn/ios.${{ matrix.platform }}.release
          echo "::endgroup::"
          echo "::group::Compress artifacts"
          zip -j ../libv8_monolith-${{ env.JOB_NAME }}-${{ matrix.platform }}.zip out.gn/ios.${{ matrix.platform }}.release/obj/libv8_monolith.a
          if [ "${{ matrix.platform }}" = "arm64" ]; then
            zip -r ../include-${{ env.JOB_NAME }}.zip include
          fi
          ls -a
          echo "::endgroup::"
      - name: Upload static library
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/libv8_monolith-${{ env.JOB_NAME }}-${{ matrix.platform }}.zip
          asset_name: libv8_monolith-${{ env.JOB_NAME }}-${{ matrix.platform }}.zip
          asset_content_type: application/zip
      - name: Upload include
        if: matrix.platform == 'arm64'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/include-${{ env.JOB_NAME }}.zip
          asset_name: include-${{ env.JOB_NAME }}.zip
          asset_content_type: application/zip

  build-win:
    name: windows
    env:
      JOB_NAME: win
    needs: create-release
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [x64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: setup env
        shell: pwsh
        run: |
          echo "${{ github.workspace }}/depot_tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "DEPOT_TOOLS_WIN_TOOLCHAIN=0" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: prepared v8 build environment
        run: |
          echo "::group::Prepare v8 build environment"
          git config --global depot-tools.allowGlobalGitConfig true
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          gclient
          fetch v8
          cd v8
          git checkout $V8_VERSION
          gclient sync
          echo "::endgroup::"
      - name: run pre-build script
        env:
          PLATFORM: ${{ matrix.platform }}
          JOB_NAME: ${{ env.JOB_NAME }}
          WORKSPACE: ${{ github.workspace }}
        run: |
          echo "::group::Run pre-build script"
          node ${{ github.workspace }}/builder.js
          echo "::endgroup::"
      - name: compile v8 static library
        shell: pwsh
        run: |
          echo "::group::Compile v8 static library"
          New-Item -ItemType directory -Path v8/out.gn/win.${{ matrix.platform }}.release/
          Copy-Item "args.win.${{ matrix.platform }}.gn" -Destination "v8/out.gn/win.${{ matrix.platform }}.release/args.gn" -force
          Set-Location -Path v8
          gn gen out.gn/win.${{ matrix.platform }}.release
          ninja v8_monolith -C out.gn/win.${{ matrix.platform }}.release/
          gn args --list out.gn/win.${{ matrix.platform }}.release
          echo "::endgroup::"
      - name: compress artifacts
        shell: pwsh
        run: |
          echo "::group::Compress artifacts"
          Compress-Archive -Path ${{ github.workspace }}/v8/out.gn/win.${{ matrix.platform }}.release/obj/v8_monolith.lib -Destination ${{ github.workspace }}/libv8_monolith-${{ env.JOB_NAME }}-${{ matrix.platform }}.zip
          if ("${{ matrix.platform }}" -eq "x64") {
            Compress-Archive -Path ${{ github.workspace }}/v8/include -Destination ${{ github.workspace }}/include-${{ env.JOB_NAME }}.zip
          }
          echo "::endgroup::"
      - name: Upload static library
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/libv8_monolith-${{ env.JOB_NAME }}-${{ matrix.platform }}.zip
          asset_name: libv8_monolith-${{ env.JOB_NAME }}-${{ matrix.platform }}.zip
          asset_content_type: application/zip
      - name: Upload include
        if: matrix.platform == 'x64'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/include-${{ env.JOB_NAME }}.zip
          asset_name: include-${{ env.JOB_NAME }}.zip
          asset_content_type: application/zip

  publish-release:
    name: publish release
    needs: [build-android, build-mac, build-ios, build-win]
    runs-on: ubuntu-latest
    steps:
    - name: Publish Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release-${{ github.ref }}
        draft: false
        prerelease: false
